### ISSUE TITLE
Uncaught TypeError: this.findBabelConfig(...).then(...).then(...).reduce is not a function

### ISSUE THREAD

**Issue by remhume** [nkt/atom-autocomplete-modules#108]
I wanted to try out the newest release to check if #99 got resolved.
Sadly it didn't get far enough for me to test 😄 

Whenever i type, i get the error `Uncaught TypeError: this.findBabelConfig(...).then(...).then(...).reduce is not a function`

Stacktrace:
```
TypeError: this.findBabelConfig(...).then(...).then(...).reduce is not a function
    at BabelLookup.getList (/Users/remmy/.atom/packages/autocomplete-modules/lib/lookups/module/babel.js:39:8)
    at relevantLookups.reduce (/Users/remmy/.atom/packages/autocomplete-modules/lib/lookups/index.js:25:16)
    at Array.reduce (<anonymous>)
    at LookupApi.filterList (/Users/remmy/.atom/packages/autocomplete-modules/lib/lookups/index.js:23:28)
    at CompletionProvider.getSuggestions (/Users/remmy/.atom/packages/autocomplete-modules/lib/completion-provider.js:53:34)
```

I believe the error is completely valid, as a promise does not have a .reduce function.
It looks like you just forgot a .then() there.

https://github.com/nkt/atom-autocomplete-modules/blob/ec34e7a4674f3cb66467166180f7affe09bdd9df/lib/lookups/module/babel.js#L39

**Comment by jonyeezs** [comment]
I found what the problem is. 

The pkg relies on bluebirdjs heavily (the `reduce`).

The injected `findBabelConfig` is still in native promise. That needs to be looked at. 

I'll try to fix it ASAP but unfortunately It's late here. So it'll have to wait. 

Thanks for contributing!

**Comment by remhume** [comment]
Gotcha!

It seems just wrapping `Promise.resolve(...)` around the findBabelConfig calls should be the easiest way of converstion

alternatively:
```javascript
findBabelConfigBluebird = (...params) => Promise.resolve(findBabelConfig(...params))
```
