### ISSUE TITLE
Uncaught TypeError: name.indexOf is not a function

### ISSUE THREAD

**Issue by Bhagath11** [nkt/atom-autocomplete-modules#128]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) package 2.2.6

### Stack Trace

Uncaught TypeError: name.indexOf is not a function

```
At C:\Users\admin\.atom\packages\autocomplete-modules\node_modules\esm-exports\lib\module.js:25

TypeError: name.indexOf is not a function
    at /packages/autocomplete-modules/node_modules/esm-exports/lib/module.js:25:14)
    at GlobalLookup.getList (/packages/autocomplete-modules/lib/lookups/export/global.js:16:17)
    at relevantLookups.reduce (/packages/autocomplete-modules/lib/lookups/index.js:25:16)
    at Array.reduce (<anonymous>)
    at LookupApi.filterList (/packages/autocomplete-modules/lib/lookups/index.js:23:28)
    at CompletionProvider.getSuggestions (/packages/autocomplete-modules/lib/completion-provider.js:64:34)
    at n.forEach.t (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:631262)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:630778)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:630516)
    at AutocompleteManager.requestNewSuggestions (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:639049)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:640140)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:504118)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:492293)
    at TextEditor.transact (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:259365)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:93878)
```

### Commands

```
     -7:47.2.0 core:copy (input.hidden-input)
     -7:42.3.0 core:paste (input.hidden-input)
     -7:40.8.0 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
     -7:37.6.0 editor:consolidate-selections (input.hidden-input)
     -7:37.6.0 core:cancel (input.hidden-input)
     -7:35.9.0 atom-beautify:beautify-editor (input.hidden-input)
     -7:27.8.0 core:save (input.hidden-input)
  2x -1:05.6.0 core:copy (input.hidden-input)
     -0:44.5.0 editor:newline (input.hidden-input)
     -0:43.9.0 core:paste (input.hidden-input)
  2x -0:39.6.0 core:move-left (input.hidden-input)
     -0:34.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:19.6.0 core:cut (input.hidden-input)
     -0:16.9.0 core:paste (input.hidden-input)
     -0:14.9.0 core:backspace (input.hidden-input)
     -0:14.5.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-modules 2.2.6 
color-picker 2.3.0 
emmet 2.4.3 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
react 0.18.0 
react-es6-snippets 0.3.0 
```

**Comment by ddaza** [comment]
I get this when I start to write the path first like this:
 - Copy the path of the desired file (with your methods) wrap in quotations
 - at the start of the line add the `import`  followed by an empty set of braces `{}` and add a `from`
 - then I look for the name of my method and plug it in at the end. 

The error will happen at this point. 

I know this is kinda backwards, but this is the only way I can reproduce it.
