### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /', require('$/: Unterminated group

### ISSUE THREAD

**Issue by forivall** [nkt/atom-autocomplete-modules#36]
1. Start typing in a require statement `foo('/bar/', require('.|cursor here|'))`

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) package, v1.5.1

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /', require('$/: Unterminated group
Unterminated group

```
At /Users/jordanklassen/.atom/packages/autocomplete-modules/src/completion-provider.js:90

SyntaxError: Invalid regular expression: /incidents', aisUser({addressBookForm: require('$/: Unterminated group
    at new RegExp (native)
    at CompletionProvider.lookupLocal (/Users/jordanklassen/.atom/packages/autocomplete-modules/src/completion-provider.js:90:65)
    at CompletionProvider.lookupGlobal (/Users/jordanklassen/.atom/packages/autocomplete-modules/src/completion-provider.js:121:19)
    at /Users/jordanklassen/.atom/packages/autocomplete-modules/src/completion-provider.js:51:24
    at Array.map (native)
    at CompletionProvider.getSuggestions (/Users/jordanklassen/.atom/packages/autocomplete-modules/src/completion-provider.js:50:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -1:24.4.0 core:paste (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -1:16 core:cut (atom-text-editor.editor.power-mode.is-focused)
     -1:15.2.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -1:13.9.0 editor:delete-line (atom-text-editor.editor.power-mode.is-focused)
     -1:13.2.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:39.8.0 core:copy (atom-text-editor.editor.power-mode.is-focused)
     -0:38.8.0 docblockr:parse-enter (atom-text-editor.editor.power-mode.is-focused)
     -0:38.8.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:30 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -0:29 docblockr:parse-enter (atom-text-editor.editor.power-mode.is-focused)
     -0:29 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:28.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:28.2.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:07.6.0 editor:move-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
     -0:07.0 editor:select-to-end-of-word (atom-text-editor.editor.power-mode.is-focused)
     -0:05.5.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "background-tips",
      "block-comment",
      "custom-invisibles",
      "dbus",
      "file-types",
      "hard-wrap",
      "language-autotools",
      "linter-flake8",
      "linter-flow",
      "linter-jshint",
      "linter-scss-lint",
      "linter-stylint",
      "pigments",
      "preview-plus",
      "recent-files-fuzzy-finder",
      "tablr",
      "tree-view-breadcrumb",
      "tree-view-git-projects",
      "welcome",
      "you-complete-me",
      "wrap-guide",
      "run-in-terminal",
      "git-wip",
      "antialiased",
      "tab-control",
      "autocomplete-paths"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".imdone",
      "tags",
      "npm-debug.log",
      "$RECYCLE.BIN",
      "*.localized"
    ],
    "packagesWithKeymapsDisabled": [
      "sort-lines",
      "emmet",
      "imdone-atom",
      "es-identifier-highlight"
    ],
    "themes": [
      "unity-ui",
      "base16-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
activate-power-mode, v0.5.2
api-workbench, v0.8.32
atom-beautify, v0.29.8
atom-mac-terminal, v1.0.4
atom-mocha, v0.0.6
atom-ternjs, v0.14.2
atom-trello, v0.5.1
auto-detect-indentation, v1.1.0
autocomplete-flow, v1.5.0
autocomplete-modules, v1.5.1
base16-syntax, v1.7.0
cursor-history, v0.5.9
docblockr, v0.7.3
dota-tips, v0.5.0
editorconfig, v1.4.1
emmet, v2.4.3
es-identifier-highlight, v0.2.11
file-icons, v1.7.15
fold-functions, v0.4.3
github-notifications, v0.1.2
graphviz-preview, v1.7.0
gtk-dark-theme, v0.1.4
highlight-selected, v0.11.2
imdone-atom, v1.3.29
imdone-atom-github, v0.1.11
language-cmake, v0.2.0
language-diff, v0.4.0
language-dot, v1.6.0
language-dots, v0.0.4
language-haxe, v0.4.4
language-jade, v0.7.1
language-json5, v1.1.0
language-lua, v0.9.4
language-mscgen, v1.3.0
language-qml, v1.0.0
language-rust, v0.4.6
language-tacoscript, v0.1.0
language-typescript-grammars-only, v1.5.0
linter, v1.11.11
linter-eslint, v7.2.4
linter-nplint, v0.3.25
linter-shellcheck, v1.2.0
linter-xo, v0.16.0
minimap, v4.24.6
minimap-autohide, v0.10.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
mscgen-preview, v1.4.0
multi-wrap-guide, v0.24.0
number-slider, v1.0.1
pane-by-type, v1.0.1
project-manager, v2.9.7
project-view, v0.5.0
raml, v0.2.0
remember-file-positions, v0.2.2
remember-folds, v0.1.0
string-case, v0.1.0
string-looper, v0.1.2
symbols-tree-view, v0.13.2
term3, v0.22.1
theme-switcher, v1.1.0
tree-view, v0.208.0
unity-ui, v2.1.5

# Dev
No dev packages
```

**Comment by forivall** [comment]
nvm dupe of #31, #34, #35
