### ISSUE TITLE
Failed to load the autocomplete-modules package

### ISSUE THREAD

**Issue by vjancik** [nkt/atom-autocomplete-modules#37]
[Enter steps to reproduce below:]

1. Just opened Atom, error appeared at initialization

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) package, v1.5.2

### Stack Trace

Failed to load the autocomplete-modules package

```
At Cannot find module 'bluebird'

Error: Cannot find module 'bluebird'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vix/.atom/packages/autocomplete-modules/src/completion-provider.js:3:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vix/.atom/packages/autocomplete-modules/src/main.js:3:28)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs",
      "pigments"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.19
auto-detect-indentation, v1.1.0
auto-update-packages, v1.0.1
autocomplete-modules, v1.5.2
autocomplete-paths, v1.0.2
color-picker, v2.1.1
docblockr, v0.7.3
editorconfig, v1.4.1
emmet, v2.4.3
file-icons, v1.7.15
highlight-selected, v0.11.2
language-babel, v2.28.0
linter, v1.11.14
linter-eslint, v7.2.4
linter-flow, v5.4.0
merge-conflicts, v1.4.4
open-recent, v5.0.0
project-manager, v2.9.7
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by nkt** [comment]
Bluebird is package dependency: https://github.com/nkt/atom-autocomplete-modules/blob/master/package.json#L22
Try to reinstall `autocomplete-modules`.
