### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by aihornmac** [nkt/atom-autocomplete-modules#43]
The syndrome is if `.babelrc` didn't use `module-alias` and Babel Plugin Module Alias Support is turned on, it throws the following error:
```
TypeError: Cannot read property '1' of undefined
    at /Users/aihornmac/.atom/packages/autocomplete-modules/src/completion-provider.js:199:43
    at CompletionProvider.lookupBabelPluginModuleAlias (/Users/aihornmac/.atom/packages/autocomplete-modules/src/completion-provider.js:222:12)
    at CompletionProvider.getSuggestions (/Users/aihornmac/.atom/packages/autocomplete-modules/src/completion-provider.js:62:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

**Comment by nkt** [comment]
Thanks for report. Fixed in 1.6.1
