### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /env')('$/: Unmatched ')'

### ISSUE THREAD

**Issue by AndrewHuffman** [nkt/atom-autocomplete-modules#5]
1. Occurs on a require statement that you immediately call a function on.

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) package, v0.3.5

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /env')('$/: Unmatched ')'

```
At /Users/andrew/.atom/packages/autocomplete-modules/src/completion-provider.js:66

SyntaxError: Invalid regular expression: /env')('$/: Unmatched ')'
  at new RegExp (native)
  at CompletionProvider.lookupLocal (/Users/andrew/.atom/packages/autocomplete-modules/src/completion-provider.js:66:65)
  at CompletionProvider.getSuggestions (/Users/andrew/.atom/packages/autocomplete-modules/src/completion-provider.js:44:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```

### Commands

```
     -0:16.5.0 whitespace:convert-tabs-to-spaces (atom-text-editor.editor)
     -0:15.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:12.7.0 editor:add-selection-above (atom-text-editor.editor.is-focused)
  3x -0:12 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:10.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:10.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:09.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "projectHome": "~/Code/Work/PZ",
    "followSymlinks": false,
    "ignoredNames": [
      ".git",
      "Thumsb.db",
      "node_modules"
    ],
    "disabledPackages": [
      "atom-terminal",
      "preview",
      "minimap",
      "linter-jshint",
      "linter-eslint"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.6
atom-jade, v0.3.0
autoclose-html, v0.17.0
autocomplete-modules, v0.3.5
editor-stats, v0.17.0
git-log, v0.3.0
jsdoc, v0.9.0
jsformat, v0.8.1
language-ejs, v0.1.0
language-fish-shell, v1.0.2
language-jade, v0.4.0
language-javascript-semantic, v0.1.0
language-swift, v0.4.0
linter, v0.12.6
merge-conflicts, v1.3.1
monokai, v0.14.0
node-debugger, v1.0.3
open-last-project, v0.4.1
project-manager, v1.15.7
script, v2.23.0
set-syntax, v0.3.0
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by nkt** [comment]
Which `path` do you enter to `require('<path>')`?

**Comment by nkt** [comment]
@AndrewHuffman ping

**Comment by AndrewHuffman** [comment]
I put in a local module, `require('./env')` but then immediate called a method, e.g., `require('./env')('env init');`

**Comment by nkt** [comment]
@AndrewHuffman I understood. Thanks for reporting!

**Comment by nkt** [comment]
Fixed.
