### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /should($/: Unterminated group

### ISSUE THREAD

**Issue by ricardofbarros** [nkt/atom-autocomplete-modules#6]
[Enter steps to reproduce below:]

1. require('./()')

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) package, v0.3.5

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /should($/: Unterminated group

```
At /Users/rbarros/.atom/packages/autocomplete-modules/src/completion-provider.js:66

SyntaxError: Invalid regular expression: /should($/: Unterminated group
  at new RegExp (native)
  at CompletionProvider.lookupLocal (/Users/rbarros/.atom/packages/autocomplete-modules/src/completion-provider.js:66:65)
  at CompletionProvider.getSuggestions (/Users/rbarros/.atom/packages/autocomplete-modules/src/completion-provider.js:44:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```

### Commands

```
     -0:10.1.0 project-switcher:toggle (atom-text-editor.editor.is-focused)
     -0:07.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "atom-jshint",
      "jslint",
      "linter-jshint"
    ],
    "themes": [
      "seti-ui",
      "base16-pretty-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
autocomplete-modules, v0.3.5
base16-pretty-dark, v0.2.3
better-handlebars, v0.1.1
docblockr, v0.7.2
git-log, v0.4.1
highlight-selected, v0.9.3
language-ejs, v0.1.0
language-jade, v0.4.0
language-swig, v0.1.0
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-js-standard, v0.2.5
project-switcher, v0.2.3
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by ricardofbarros** [comment]
This happens when I type `()` inside `require`

**Comment by nkt** [comment]
@ricardofbarros yep, it's bug, but it's hack, can you suggest at least one real case where it's needed?

**Comment by ricardofbarros** [comment]
No real use case and I dont intend to use this hack, it is just simply annoying that an error pops out when I mistakenly type a parenthese

**Comment by nkt** [comment]
@ricardofbarros, I'll think how to fix this. This is not first bug, relative to generated regexp, I guess I'll add `try-catch` around matching.
Thanks for reporting!

**Comment by ricardofbarros** [comment]
Yeah that would be great :+1:

**Comment by nkt** [comment]
Fixed
