### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by benpptung** [nkt/atom-autocomplete-modules#70]
[Enter steps to reproduce:]

1. install atom-smart-template
2. In Tree View, right click a folder and choose 'Create files from template'
3. In Template selection list, typing to select template, then..see this TypeError.

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.9.5
**Thrown From**: [autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) package 1.6.10

### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At /Users/benpptung/.atom/packages/autocomplete-modules/node_modules/fuzzaldrin/lib/scorer.js:60

TypeError: string.indexOf is not a function
    at Object.exports.score (/packages/autocomplete-modules/node_modules/fuzzaldrin/lib/scorer.js:60:31)
    at module.exports (/packages/autocomplete-modules/node_modules/fuzzaldrin/lib/filter.js:25:24)
    at filter (/packages/autocomplete-modules/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at MySelectListView.module.exports.SelectListView.populateList (/packages/atom-smart-template/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
    at /packages/atom-smart-template/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```

### Commands

```
     -2:35.7.0 atom-smart-template:create-files-from-template (span.name.icon.icon-file-directory)
     -2:15.2.0 core:confirm (input.hidden-input)
  2x -1:18.6.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:42.9.0 settings-view:open (input.hidden-input)
     -0:31.7.0 atom-smart-template:create-files-from-template (span.name.icon.icon-file-directory)
     -0:26.7.0 core:move-down (input.hidden-input)
     -0:26.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-monokai 0.10.9 
atom-smart-template 0.3.2 
autocomplete-modules 1.6.10 
busy-signal 1.4.3 
code-peek 1.4.21 
dbclick-tree-view 1.6.0 
docblockr 0.11.0 
intentions 1.1.5 
language-html-swig 2.0.1 
language-r 0.4.1 
linter 2.2.0 
linter-annotations 1.0.1 
linter-jshint 3.1.5 
linter-ui-default 1.6.7 
monokai 0.24.0 
monokai-2 2.8.1 
monokai-complete-syntax 2.0.1 
monokai-slate 0.6.0 
one-dark-monokai-syntax 1.0.0 
one-monokai 0.3.0 
selection-highlight 0.1.6 
```

**Comment by benpptung** [comment]
no problem in new atom.
