### ISSUE TITLE
Failed to activate the autocomplete-modules package

### ISSUE THREAD

**Issue by Nufflee** [nkt/atom-autocomplete-modules#77]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-modules](https://github.com/nkt/atom-autocomplete-modules) package 1.7.2

### Stack Trace

Failed to activate the autocomplete-modules package

```
At Cannot find module 'json5'

Error: Cannot find module 'json5'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.0-beta0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-modules/node_modules/find-babel-config/lib/index.js:5:13)
    at /packages/autocomplete-modules/node_modules/find-babel-config/lib/index.js:151:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-modules/src/completion-provider.js:9:25)
    at /packages/autocomplete-modules/src/completion-provider.js:280:37)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-modules/src/main.js:3:28)
    at /packages/autocomplete-modules/src/main.js:63:50)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/package.js:1030:34
```

### Commands

```
     -0:26.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-ide-ui 0.4.0 
autocomplete-modules 1.7.2 
autocomplete-paths 2.11.0 
color-picker 2.2.5 
file-icons 2.1.12 
highlight-selected 0.13.1 
ide-csharp 0.6.0 
ide-css-less-scss 0.1.1 
ide-html 0.3.0 
ide-typescript 0.6.1 
minimap-pigments 0.2.2 
new-tab 0.5.3 
open-conemu-here 0.5.0 
open-recent 5.0.0 
package-sync 1.1.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
react 0.16.2 
react-es6-snippets 0.3.0 
react-snippets 0.9.0 
tab-switcher 1.5.6 
```

**Comment by nkt** [comment]
Try to reinstall this package.

**Comment by jonyeezs** [comment]
Hi @Nufflee did that help resolve your issue?

**Comment by Nufflee** [comment]
Yes. @jonyeezs
